# Generated by Django 6.0.7 on 2026-07-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTrackingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prayer_name', models.CharField(choices=[('Bomdod', 'Bomdod'), ('Peshin', 'Peshin'), ('Asr', 'Asr'), ('Shom', 'Shom'), ('Xufton', 'Xufton')], max_length=20)),
                ('status', models.CharField(choices=[('on_time', 'On time'), ('late', 'Late'), ('qaza', 'Qaza'), ('not_tracked', 'Not tracked')], default='not_tracked', max_length=20)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
