# Generated by Django 6.0.7 on 2026-07-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayertrackingrecord',
            name='prayer_name',
            field=models.CharField(choices=[('Bomdod', 'Bomdod'), ('Peshin', 'Peshin'), ('Asr', 'Asr'), ('Shom', 'Shom'), ('Xufton', 'Xufton'), ('Vitr', 'Vitr')], max_length=20),
        ),
    ]
