# Generated by Django 6.0.7 on 2026-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_prayertrackingrecord_prayer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayertrackingrecord',
            name='status',
        ),
        migrations.AddField(
            model_name='prayertrackingrecord',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
