# Generated by Django 6.0.7 on 2026-07-14 10:32

import apps.notifications.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_offsets_minutes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=apps.notifications.models.default_enabled_offsets)),
                ('enabled_prayers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=apps.notifications.models.default_enabled_prayers)),
                ('sound_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
