# Generated by Django 6.0.7 on 2026-10-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='use_custom_times',
            field=models.BooleanField(default=False),
        ),
    ]
