# Generated by Django 6.0.7 on 2026-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationsettings_use_custom_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='reminder_sound',
            field=models.CharField(choices=[('klassik', 'klassik'), ('yumshoq', 'yumshoq'), ('signal', 'signal'), ('uygonish', 'uygonish'), ('raqamli', 'raqamli')], default='klassik', max_length=20),
        ),
    ]
