# Generated by Django 6.0.7 on 2026-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationsettings_reminder_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='reminder_sound',
            field=models.CharField(choices=[('klassik', 'klassik'), ('yumshoq', 'yumshoq'), ('signal', 'signal'), ('uygonish', 'uygonish'), ('raqamli', 'raqamli'), ('allohning_99_ismi', 'allohning_99_ismi')], default='klassik', max_length=20),
        ),
    ]
