# Generated by Django 6.0.7 on 2026-07-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fajr', models.TimeField(blank=True, null=True)),
                ('dhuhr', models.TimeField(blank=True, null=True)),
                ('asr', models.TimeField(blank=True, null=True)),
                ('maghrib', models.TimeField(blank=True, null=True)),
                ('isha', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
