# Generated by Django 6.0.7 on 2026-07-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon_name', models.CharField(default='menu_book', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Dua categories',
            },
        ),
        migrations.CreateModel(
            name='Dua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('arabic_text', models.TextField()),
                ('transliteration', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duas', to='dua.duacategory')),
            ],
        ),
    ]
