# Generated by Django 6.0.7 on 2026-10-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dua', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dua',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dua_images/'),
        ),
    ]
