# Generated by Django 6.0.7 on 2026-10-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dua', '0002_dua_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='duacategory',
            name='inline_images',
            field=models.BooleanField(default=False),
        ),
    ]
