# Generated by Django 6.0.7 on 2026-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dua', '0003_duacategory_inline_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='dua',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
