# Generated by Django 6.0.7 on 2026-07-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name_arabic', models.CharField(max_length=100)),
                ('name_latin', models.CharField(max_length=100)),
                ('name_translation', models.CharField(blank=True, max_length=150)),
                ('ayah_count', models.PositiveSmallIntegerField()),
                ('pdf_url', models.URLField()),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
