# Generated by Django 6.0.7 on 2026-10-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surah',
            name='video_url',
        ),
        migrations.CreateModel(
            name='SurahAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('reciter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surah_audios', to='quran.reciter')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='quran.surah')),
            ],
            options={
                'ordering': ['surah__number'],
                'unique_together': {('surah', 'reciter')},
            },
        ),
    ]
