# Generated by Django 6.0.7 on 2026-10-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_remove_surah_video_url_surahaudio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciter',
            options={'ordering': ['name']},
        ),
    ]
